@echo off

set BUILD_SYSTEM=Visual Studio 17 2022
set BUILD_TAG=vs2022
set THIRDPARTY_LLVM_DIR=%cd%\externals\llvm-project
set BUILD_DIR=%THIRDPARTY_LLVM_DIR%\build
set INSTALL_DIR=%THIRDPARTY_LLVM_DIR%\install

mkdir %BUILD_DIR%
mkdir %INSTALL_DIR%

cd %BUILD_DIR%

cmake ..\llvm -G "%BUILD_SYSTEM%" ^
      -DCMAKE_INSTALL_PREFIX=%INSTALL_DIR% ^
      -DLLVM_LOCAL_RPATH=%INSTALL_DIR%\lib ^
      -DLLVM_PARALLEL_COMPILE_JOBS=7 ^
      -DLLVM_PARALLEL_LINK_JOBS=1 ^
      -DLLVM_BUILD_EXAMPLES=OFF ^
      -DLLVM_INSTALL_UTILS=ON ^
      -DCMAKE_BUILD_TYPE=Release ^
      -DLLVM_ENABLE_ASSERTIONS=ON ^
      -DLLVM_CCACHE_BUILD=OFF ^
      -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ^
      -DLLVM_ENABLE_PROJECTS="mlir"

cmake --build . --target check-mlir

cd %cd%
